### PR TITLE
rst expects a blank line to thread a block as a list

### PR DESCRIPTION
**Pull request by Psycojoker**

### CODE REVIEW

**Comment by tardyp** [comment]
I am not sure if we want to improve the documentation of a 6 year old release of buildbot. Please upgrade!

**Comment by Psycojoker** [comment]
Oh, were is supposed to be the new documentation then? That the only occurrence of this page http://docs.buildbot.net/current/manual/cfg-changesources.html#choosing-a-change-source (were this bug is still present) that I could find in the github organisation searching for strings of this page: https://github.com/search?q=org%3Abuildbot+%22There+are+a+variety+of%22+ChangeSource+%22classes+available%2C%22&ref=searchresults&type=Code&utf8=%E2%9C%93

Or is the doc not published anymore online?

**Comment by djmitche** [comment]
We use this repository as a way to deploy the docs.buildbot.net website, so the content you modified was added when 0.8.5 was released.  I think that since that release we have stopped including the .txt files in the bbdocs repository.

The source for this documentation is https://github.com/buildbot/buildbot/blob/master/master/docs/manual/cfg-changesources.rst and as you can see in the raw view there, this issue has already been fixed in https://github.com/buildbot/buildbot/commit/19d429c8a3a41b7f16e67633713e40edbc6d1aee

**Comment by Psycojoker** [comment]
Well, it looks like the master documentation hasn't been deployed yet https://docs.buildbot.net/current/manual/cfg-changesources.html#choosing-a-change-source (sorry, I should have given this link at the beginning)

**Pull request closed without merging**
